name: Build and Test

on:
  push:
    branches:
      - '**' 
  pull_request:
    branches:
      - '**' 

jobs:
  lint-code:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        # Full git history is needed to get a proper
        # list of changed files within `super-linter`
        fetch-depth: 0

    - name: Run super-linter
      uses: super-linter/super-linter@v5
      env:
        DISABLE_ERRORS: true
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-MOLE:
    runs-on: ubuntu-latest
    needs: lint-code

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache build directory
      uses: actions/cache@v3
      with:
        path: build
        key: build-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          build-${{ runner.os }}-

    - name: Update Libraries
      run: sudo apt-get update

    - name: Install dependencies
      run: |
        sudo apt-get install -y cmake g++ libgtest-dev libarmadillo-dev libopenblas-dev libsuperlu-dev libeigen3-dev
        # Build and install Google Test (if not pre-installed)
        cd /usr/src/googletest && sudo cmake . && sudo make && sudo make install

    - name: Create build directory
      run: mkdir build

    - name: Run CMake
      run: cmake -S . -B build

    - name: Build MOLE library
      run: cmake --build build

  run-tests:
    runs-on: ubuntu-latest
    needs: build-MOLE

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Restore build cache
      uses: actions/cache@v3
      with:
        path: build
        key: build-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          build-${{ runner.os }}-

    - name: Run tests
      run: |
        cd build
        make run_tests
  
