---
name: Build and Test

on:
  push:
    branches:
      - '**' 
  pull_request:
    branches:
      - '**' 

jobs:
  # lint-code:
  #   runs-on: ubuntu-latest

  #   permissions:
  #     contents: read
  #     packages: read
  #     statuses: write
      
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         # Full git history is needed to get a proper
  #         # list of changed files within `super-linter`
  #         fetch-depth: 0

  #     - name: Run super-linter
  #       uses: super-linter/super-linter/slim@v5
  #       env:
  #         DISABLE_ERRORS: true
  #         VALIDATE_ALL_CODEBASE: false
  #         DEFAULT_BRANCH: master
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-MOLE-ubuntu:
    runs-on: ubuntu-latest
    needs: lint-code

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update Libraries
      run: sudo apt-get update

    - name: Install dependencies
      run: |
        sudo apt-get install -y cmake g++ libgtest-dev libarmadillo-dev libopenblas-dev libsuperlu-dev libeigen3-dev
        cd /usr/src/googletest && sudo cmake . && sudo make && sudo make install

    - name: Create build directory
      run: mkdir -p build

    - name: Run CMake
      run: cmake -S . -B build

    - name: Build MOLE library
      run: cmake --build build

    - name: Run tests
      run: |
        cd build
        make run_tests

  build-MOLE-macOSX:
    runs-on: macOS-latest
    needs: lint-code

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Fix Homebrew
    #   run: |
    #     sudo chown -R $(whoami) /usr/local/Cellar
    #     git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
    #     brew uninstall --ignore-dependencies java
    #     brew update
        
    - name: Install dependencies
      run: |
        brew install gfortran cmake openblas eigen libomp lapack
        FC = /opt/homebrew/Cellar/gcc/14.2.0_1/bin/gfortran
        export LDFLAGS="-L/opt/homebrew/opt/openblas/lib"
        export CPPFLAGS="-I/opt/homebrew/opt/openblas/include"
        export PKG_CONFIG_PATH="/opt/homebrew/opt/openblas/lib/pkgconfig"

        export LDFLAGS="-L/opt/homebrew/opt/libomp/lib"
        export CPPFLAGS="-I/opt/homebrew/opt/libomp/include"

        export LDFLAGS="-L/opt/homebrew/opt/lapack/lib"
        export CPPFLAGS="-I/opt/homebrew/opt/lapack/include"
        export PKG_CONFIG_PATH="/opt/homebrew/opt/lapack/lib/pkgconfig"

    - name: Check compiler versions
      run: |
        gfortran --version
        which gfortran
        gcc --version
        g++ --version

    - name: Create build directory
      run: mkdir -p build

    - name: Run CMake
      run: cmake -S . -B build

    - name: Build MOLE library
      run: cmake --build build

    - name: Run tests
      run: |
        cd build
        make run_tests

  # Compile-JOSS-paper:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4

  #   - name: Build draft PDF
  #     uses: openjournals/openjournals-draft-action@master
  #     with:
  #       journal: joss
  #       paper-path: doc/papers/joss/paper.md

  #   - name: Upload a Build Artifact
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: paper
  #       path: doc/papers/joss/paper.pdf
